### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by nkhumphreys** [awa/go-iap#104]
When validating ios receipt data, some of the receipts are failing the client.Verify call with the following error

```
invalid character '<' looking for beginning of value
```

The data is the raw base64 encoded string that the app receives.  Having passed the data through base64 decode using the following site https://www.base64decode.org/ it would appear that changing the charset from UTF-8 to ASCII means the receipt then decodes as expected, but given this is only happening for some receipts and not others I believe the issue is better fixed in this library.  

Any thoughts on what might be causing this?

**Comment by ojrac** [comment]
This might not be your issue, but sometimes Apple returns an HTML document from their API (I've seen it happen when there's some kinds of server error), and it gets passed to the JSON parser. Pull request #103 was our fix.

It also looks like Apple's servers are in a weird place right now, returning a "200 OK" response along with an HTML page: https://forums.developer.apple.com/thread/128335
