### ISSUE TITLE
SubscriptionNotification don't have fields `bid` and `bvrs`

### ISSUE THREAD

**Issue by zzn01** [awa/go-iap#135]
according to the [doc](https://developer.apple.com/documentation/appstoreservernotifications/responsebody): there should be `bid` and `bvrs` in struct [SubscriptionNotification](https://github.com/awa/go-iap/blob/master/appstore/notification.go#L69).
![image](https://user-images.githubusercontent.com/11185913/102066602-fbe14c80-3e34-11eb-8ee3-f2c9abb2c4bb.png)

**Comment by takecy** [comment]
Thanks for pointing that out.
I've added it, please check it out
