### ISSUE TITLE
Support OAuth client/token (instead of json service account key) in playstore

### ISSUE THREAD

**Issue by benhxy** [awa/go-iap#180]
Service account key is not a good security practice (https://cloud.google.com/iam/docs/best-practices-for-managing-service-account-keys#alternatives)

It would be better to have anther New() method that takes a https://pkg.go.dev/golang.org/x/oauth2@v0.4.0#TokenSource.

Alternatively, accept a https://pkg.go.dev/golang.org/x/oauth2/google#DefaultClient that already contains the token.

**Comment by benhxy** [comment]
I'd be happy to contribute to this issue =)

**Comment by richzw** [comment]
Close it since the PR is merged.
