### ISSUE TITLE
Cannot get token from ParseNotificationV2 func

### ISSUE THREAD

**Issue by Daydaylw3** [awa/go-iap#202]
here is the case

```golang
import (
	"time"

	"github.com/awa/go-iap/appstore"
	"github.com/golang-jwt/jwt/v4"
)

// it is too long, i make short here
var signedPayload  = `eyJhbGciOiJFUzI1...`

func main() {
	token := &jwt.Token{}
	if err := appstore.New().ParseNotificationV2(signedPayload, token); err != nil {
		panic(err)
	}
}
```

and no matter ``token`` is a struct or pointer, just cannot be parsed.

![image](https://github.com/awa/go-iap/assets/38597251/9d2eb288-06ab-4e1e-a0cb-dee783067e04)

but actually in ``ParseNotificationV2`` there are not empty

![image](https://github.com/awa/go-iap/assets/38597251/d0cd25ed-42ff-4cd0-aa45-9f0ee82be48c)

**Comment by richzw** [comment]
Is there any error returned from `ParseNotificationV2`?

**Comment by Daydaylw3** [comment]
> 

no, is the token always be empty

**Comment by Daydaylw3** [comment]
and i have made a pr to fix that, could @richzw help me to review? thx~

**Comment by MakDon** [comment]
IMHO, it is better that use `ParseNotificationV2(tokenStr string) (result *jwt.Token, err error)` as the method signature.

**Comment by richzw** [comment]
> IMHO, it is better that use `ParseNotificationV2(tokenStr string) (result *jwt.Token, err error)` as the method signature.

Yes, It could be better to use `ParseNotificationV2(tokenStr string) (result *jwt.Token, err error)`. To use this method `ParseNotificationV2(tokenStr string, result *jwt.Token) error` just follow the same signature of `Verify` and `VerifyWithStatus`

**Comment by richzw** [comment]
> and i have made a pr to fix that, could @richzw help me to review? thx~

Thank you very much for your help. I will review your PR ASAP

**Comment by Daydaylw3** [comment]
It is ok right now~ 

![image](https://github.com/awa/go-iap/assets/38597251/4215243a-44f8-4819-93cd-69bd4e8d82cc)

Thanks for support @richzw 
So quick👍
