### ISSUE TITLE
When using App Store Server API, is get_transaction_info enough for a consumable product verification?

### ISSUE THREAD

**Issue by kaijietti** [awa/go-iap#209]
I'm new to App Store Server API, and I found that there is an API called `GetTransactionInfo` to fetch information about an transaction using only `transaction_id`. I want to know that is this API providing enough information for me to do simple verification for consumable product purchase (which should be an one time purchase/transaction without too many complicated states) instead of using `GetTransactionHistory` (which seems frequently used in subscription, but the structure is complicated for a consumable product)? As `GetTransactionInfo` is returning only one transaction info for this `transaction_id`, I also want to learn that can a consumable product purchase has more than one transaction history (like purchased state and refunded state or something else)? This issue is not to report a bug but instead sincerely asking for experience :sob:.

**Comment by richzw** [comment]
Currently, the [verify](https://github.com/awa/go-iap/blob/master/appstore/validator.go#L115) api is used on my server side for the consumable product receipt verification. However, the `verifyReceipt` could be deprecated per this [doc](https://developer.apple.com/documentation/appstorereceipts/verifyreceipt?changes=latest_minor)

> Deprecated
> The verifyReceipt endpoint is deprecated. To validate receipts on your server, follow the steps in [Validating receipts on the device](https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device?changes=latest_minor) on your server. To validate in-app purchases on your server without using receipts, call the [App Store Server API](https://developer.apple.com/documentation/appstoreserverapi?changes=latest_minor) to get Apple-signed transaction and subscription information for your customers, or verify the [AppTransaction](https://developer.apple.com/documentation/storekit/apptransaction?changes=latest_minor) and [Transaction](https://developer.apple.com/documentation/storekit/transaction?changes=latest_minor) signed data that your app obtains. You can also get the same signed transaction and subscription information from the [App Store Server Notifications V2](https://developer.apple.com/documentation/appstoreservernotifications/app_store_server_notifications_v2?changes=latest_minor) endpoint.

> I want to know that is this API providing enough information for me to do simple verification for consumable product purchase (which should be an one time purchase/transaction without too many complicated states) instead of using GetTransactionHistory (which seems frequently used in subscription, but the structure is complicated for a consumable product)? 

IMO, using `GetTransactionInfo` API to fetch information of one transaction per `transaction_id` for  consumable product is enough.

> As GetTransactionInfo is returning only one transaction info for this transaction_id, I also want to learn that can a consumable product purchase has more than one transaction history (like purchased state and refunded state or something else)? 

Based on my knowledge, there is only one receipt for the consumable product. As for the refund information, you could use `Get Refund History` API.
