### ISSUE TITLE
PriceIncreaseStatus in JWSRenewalInfoDecodedPayload should be *int32

### ISSUE THREAD

**Issue by Daydaylw3** [awa/go-iap#232]
The [``PriceIncreaseStatus``](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L96C2-L96C2) field in ``JWSRenewalInfoDecodedPayload`` should be ``*int32`` would more appropriate, cause base on [Apple Doc](https://developer.apple.com/documentation/appstoreserverapi/priceincreasestatus), it only have 2 possible value(0, 1). 

> 0 - The customer hasn’t yet responded to an auto-renewable subscription price increase that requires customer consent.
> 
> 1 - The customer consented to an auto-renewable subscription price increase that requires customer consent, or the App Store has notified the customer of an auto-renewable subscription price increase that doesn’t require consent.

But in the old [Apple Doc](https://developer.apple.com/documentation/appstorereceipts/responsebody/pending_renewal_info), this field is ``string`` type. So, when non price_increase happened, this field would be empty. 
So the same with the new api

```json
{
    "autoRenewProductId": "${autoRenewProductId}",
    "autoRenewStatus": 0,
    "environment": "Sandbox",
    "expirationIntent": 1,
    "isInBillingRetryPeriod": false,
    "originalTransactionId": "2000000394545223",
    "productId": "${productId}",
    "recentSubscriptionStartDate": 1692610707000,
    "renewalDate": 1692611727000,
    "signedDate": 1692774746958
}
```

But if ``PriceIncreaseStatus`` is ``int32``, will be decoded to ``0``, which indicated that 

> The customer hasn’t yet responded to an auto-renewable subscription price increase that requires customer consent. 

That would be odd.

So the same with the [``ExpirationIntent``](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L90C33-L90C33), [relative doc](https://developer.apple.com/documentation/appstoreserverapi/expirationintent)

the [``OfferType``](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L149C30-L149C30) in ``JWSTransaction``, [relative doc](https://developer.apple.com/documentation/appstoreserverapi/offertype)

the [``RevocationReason``](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L152C7-L152C7) in ``JWSTransaction``, [relative doc](https://developer.apple.com/documentation/appstoreserverapi/revocationreason)

```json
{
    "transactionId": "${transactionId}",
    "originalTransactionId": "${originalTransactionId}",
    "webOrderLineItemId": "${webOrderLineItemId}",
    "bundleId": "${bundleId}",
    "productId": "${productId}",
    "subscriptionGroupIdentifier": "21375857",
    "purchaseDate": 1692777326000,
    "originalPurchaseDate": 1692776648000,
    "expiresDate": 1692777506000,
    "quantity": 1,
    "type": "Auto-Renewable Subscription",
    "inAppOwnershipType": "PURCHASED",
    "signedDate": 1692777349608,
    "storefront": "MAC",
    "storefrontId": "143515",
    "transactionReason": "RENEWAL",
    "environment": "Sandbox"
}
```

**Comment by Daydaylw3** [comment]
And I make a [PR](https://github.com/awa/go-iap/pull/233) to resolve that 🥶

**Comment by Daydaylw3** [comment]
> @Daydaylw3 , thank you for your PR. Here is one question, there is NO zero value of expirationIntent and offerType , maybe it could be better to keep the original type rather than *int32.

fair enough!

**Comment by Daydaylw3** [comment]
And I also found that [``IsInBillingRetryPeriod``](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L92C8-L92C8) is the same, how do you think about it?

[Old Apple Doc](https://developer.apple.com/documentation/appstorereceipts/is_in_billing_retry_period), [New Apple Doc](https://developer.apple.com/documentation/appstoreserverapi/isinbillingretryperiod)

**Comment by richzw** [comment]
> And I also found that [`IsInBillingRetryPeriod`](https://github.com/awa/go-iap/blob/34bac7bd12d3cd730081d27a5cb2556b5947a153/appstore/api/model.go#L92C8-L92C8) is the same, how do you think about it?
> 
> [Old Apple Doc](https://developer.apple.com/documentation/appstorereceipts/is_in_billing_retry_period), [New Apple Doc](https://developer.apple.com/documentation/appstoreserverapi/isinbillingretryperiod)

I just added my comment in the PR review.

**Comment by Daydaylw3** [comment]
Thank you for so quick react and patient :) 👍
