### ISSUE TITLE
Wrong type of consumptionState field

### ISSUE THREAD

**Issue by dominiclvrpl** [awa/go-iap#252]
https://github.com/awa/go-iap/blob/99e3f2105a3e90298d7edd9e762de4940ec52c79/hms/model.go#L58C22-L58C22

According to [docs](https://developer.huawei.com/consumer/en/doc/HMSCore-References-V5/server-data-model-0000001050986133-V5) this field must be int

Also consts must be int 
https://github.com/awa/go-iap/blob/99e3f2105a3e90298d7edd9e762de4940ec52c79/hms/model.go#L353
https://github.com/awa/go-iap/blob/99e3f2105a3e90298d7edd9e762de4940ec52c79/hms/model.go#L354
and values must be
InAppPurchaseDataConsumptionStateNotConsumed int = 0
InAppPurchaseDataConsumptionStateConsumed    int = 1

**Comment by richzw** [comment]
@dominiclvrpl Thank you very much for this issue. It could be fixed later....
