### ISSUE TITLE
how to parse transaction id by receipt ？？

### ISSUE THREAD

**Issue by SFLAQiu** [awa/go-iap#258]
App store Server API 
/inApps/v1/history/{TransactionId}  need TransactionId

Our ideas：
app -> receipt => server -> receipt=> parse transaction id =>  appsotre-api

but：
server  parse transaction id Blocked

appstore => App Store Server LibraryReceiptUtility::getTransactionldFromAppReceipt
appstore had Java、Swift、Python、Node.js  SDK，but no go

go-iap Is it supported ?  I couldn't find it

**Comment by richzw** [comment]
Per history API https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history

> GET https://api.storekit.itunes.apple.com/inApps/v1/history/{transactionId}

The `transactionId` should be used in this API, and as far as I know, there is no API to reflect the transctionID from the raw receipt. Please correct me if something is missing.

-------

As for retrieving the transactionId from the receipt on the app (client side), the [` transactionIdentifier`](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411288-transactionidentifier) of `SKPaymentTransaction` is the transactionId.

**Comment by SFLAQiu** [comment]
> Per history API https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history
> 
> > GET [https://api.storekit.itunes.apple.com/inApps/v1/history/{transactionId}](https://api.storekit.itunes.apple.com/inApps/v1/history/%7BtransactionId%7D)
> 
> The `transactionId` should be used in this API, and as far as I know, there is no API to reflect the transctionID from the raw receipt. Please correct me if something is missing.
> 
> One work around could be, first call `client.Verify` with raw receipt, and get the transactionId from this API. Then call the history API with this transactionId.
> 
> As for retrieving the transactionId from the receipt on the app (client side), the [` transactionIdentifier`](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411288-transactionidentifier) of `SKPaymentTransaction` is the transactionId.
> 
> Then, the client sends the transactionId to the server, and this transactionId is used to ios server API on the server side.
> 
> Could you please share some logic of `App Store Server LibraryReceiptUtility::getTransactionldFromAppReceipt` ?

感谢老铁的回复。直接CH 交流吧。

早前我接入的是 verifyReceipt API，看官方文档已经弃用，客户端上传给服务端的是票据。
然后看到一篇文章是可以通过票据解析出transation_id，没有go，也查不到相关开源的实现，所以这里就疑惑了。
App Store Server LibraryReceiptUtility::getTransactionldFromAppReceipt ，这个我是看掘金的一篇文章：
[文章地址](https://juejin.cn/post/7254373662455185469)
![Snipaste_2024-01-22_18-50-10](https://github.com/awa/go-iap/assets/5511901/67df9c24-9101-4f20-bb8f-2b98ea719c7e)

官方提供的 SDK 里确定也是有提供 getTransactionldFromAppReceipt 方法，直接把票据解码出来。

在这之前我是不确定在交易后客户端能否难道 transation_id，现在也还在和客户端确认中，看文档应该是可以在客户端拿到吧？
最终确认下，你做过苹果的订阅的流程是走客户端上报：transaction_id 吗？

**Comment by richzw** [comment]
> > Per history API https://developer.apple.com/documentation/appstoreserverapi/get_transaction_history
> > > GET [https://api.storekit.itunes.apple.com/inApps/v1/history/{transactionId}](https://api.storekit.itunes.apple.com/inApps/v1/history/%7BtransactionId%7D)
> > 
> > 
> > The `transactionId` should be used in this API, and as far as I know, there is no API to reflect the transctionID from the raw receipt. Please correct me if something is missing.
> > One work around could be, first call `client.Verify` with raw receipt, and get the transactionId from this API. Then call the history API with this transactionId.
> > As for retrieving the transactionId from the receipt on the app (client side), the [` transactionIdentifier`](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411288-transactionidentifier) of `SKPaymentTransaction` is the transactionId.
> > Then, the client sends the transactionId to the server, and this transactionId is used to ios server API on the server side.
> > Could you please share some logic of `App Store Server LibraryReceiptUtility::getTransactionldFromAppReceipt` ?
> 
> 感谢老铁的回复。直接CH 交流吧。
> 
> 早前我接入的是 verifyReceipt API，看官方文档已经弃用，客户端上传给服务端的是票据。 然后看到一篇文章是可以通过票据解析出transation_id，没有go，也查不到相关开源的实现，所以这里就疑惑了。 App Store Server LibraryReceiptUtility::getTransactionldFromAppReceipt ，这个我是看掘金的一篇文章： [文章地址](https://juejin.cn/post/7254373662455185469) ![Snipaste_2024-01-22_18-50-10](https://private-user-images.githubusercontent.com/5511901/298552486-67df9c24-9101-4f20-bb8f-2b98ea719c7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjE0MzUsIm5iZiI6MTcwNTkyMTEzNSwicGF0aCI6Ii81NTExOTAxLzI5ODU1MjQ4Ni02N2RmOWMyNC05MTAxLTRmMjAtYmI4Zi0yYjk4ZWE3MTljN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTA1ODU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTIyMGMyYjcwNTc2ODdkNTQ0ZGZmZWMzMTFlY2E2YTBlOGY1MGU1NDE2ZDg5Njc0ZGFhMDc0ZDFkNmFlMDk5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.A-_pO_exOexRTN_rOQ6AZaATh8EpNAU8nnqgCGQxHL8)
> 
> 官方提供的 SDK 里确实也是有提供 getTransactionldFromAppReceipt 方法，直接把票据解码出来。
> 
> 在这之前我是不确定在交易后客户端能否拿到 transation_id 现在也还在和客户端确认中，看文档应该是可以在客户端拿到吧？

Yes

> 最终确认下，你做过苹果的订阅的流程是走客户端上报：transaction_id 吗？

Yes

**Comment by SFLAQiu** [comment]
忘记回复了，客户端能够拿到 transation_id

**Comment by alkanyunus** [comment]
Why dont you write in english though?
