### ISSUE TITLE
offerDiscountType is missing in JWSTransactionDecodedPayload

### ISSUE THREAD

**Issue by yoshiken** [awa/go-iap#266]
In the server notification from Apple, offerDiscountType exists in the documentation and in the actual payload, but it is not present 

in the code. The Transaction obtained by querying the API contains this field, so a similar implementation is required.

https://developer.apple.com/documentation/appstoreservernotifications/offerdiscounttype

https://github.com/awa/go-iap/blob/1579b864445c2539e6321e15d5b0d3df62786985/appstore/notification_v2.go#L211-L236

https://github.com/awa/go-iap/pull/251/files

**Comment by richzw** [comment]
@yoshiken Thank you very much for your report, It will be fixed.

**Comment by yoshiken** [comment]
@richzw thx! 😘
