### ISSUE TITLE
Is there more detail error msg when verify google iap

### ISSUE THREAD

**Issue by kkfrank2** [awa/go-iap#269]
In my production, I got error when veirfy google iap,  i used this method  
playStoreClient.VerifyProduct(ctx, pkgname, productId, purchaseToken)

```
{
  "error": {
    "code": 400,
    "message": "Invalid Value",
    "errors": [
      {
        "message": "Invalid Value",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```
how can I know more detail, is a user problem(for example, user hack?), or my code problem.  Can you give me some tips

**Comment by richzw** [comment]
@kkfrank2 , here is some discussion about this error  `Invalid Value`.  https://stackoverflow.com/questions/46055214/google-play-developer-api-400-invalid-value-inapppurchases. 

Another option is to validate the receipt through [`VerifySignature`](https://github.com/awa/go-iap/blob/master/playstore/validator.go#L286) to do local verification for this receipt.

**Comment by richzw** [comment]
> > VerifySignature
> 
> Thanks for your repley. Do you konw the google purchaseToken in this method, VerifyProduct(ctx, pkgname, productId, purchaseToken), is always the same fixed length. I found the failed token's length is different with the success one. So I somewhat suspect this pruchase is not legal

As for the length of purchase token, there is one discussion here https://stackoverflow.com/questions/62707980/what-is-the-maximum-length-of-google-play-billing-purchase-token.

**Comment by kkfrank2** [comment]
多谢。后面查了下，没有更多的发现。 问题就先关了
