### ISSUE TITLE
Sandbox 401 error by appstore server api

### ISSUE THREAD

**Issue by takeone90** [awa/go-iap#283]
I'm migrating the App Store Server API for iOS.
I understand that Sandbox and Production differ only in their endpoints (with KeyID, BundleID, Issuer, and KeyContent being the same). However, when I call GetTransactionInfo() with the TransactionID of a Sandbox receipt, I receive a 401 response. 

- When verifying with verifyReceipt(), the response shows 'environment: Sandbox'.
- The Production environment processes real receipts correctly. (Same KeyID, BundleID, Issuer, and KeyContent)

Please help.

**Comment by richzw** [comment]
You may get the details of the error from app store api error https://github.com/awa/go-iap/blob/master/appstore/api/store.go#L583, you could find more error information from `errorMessage`, related docs https://developer.apple.com/documentation/appstoreserverapi/error_codes  @takeone90

**Comment by takeone90** [comment]
> You may get the details of the error from app store api error https://github.com/awa/go-iap/blob/master/appstore/api/store.go#L583, you could find more error information from `errorMessage`, related docs https://developer.apple.com/documentation/appstoreserverapi/error_codes @takeone90

First off, thanks for your reply.
I checked the part you mentioned about newAppStoreAPIError(), and the StatusCode is 401 with an empty bodyBytes, so it returns 'nil, false'. Is this an issue with the API server?

**Comment by richzw** [comment]
> > You may get the details of the error from app store api error https://github.com/awa/go-iap/blob/master/appstore/api/store.go#L583, you could find more error information from `errorMessage`, related docs https://developer.apple.com/documentation/appstoreserverapi/error_codes @takeone90
> 
> First off, thanks for your reply. @richzw I checked the part you mentioned about newAppStoreAPIError(), and the StatusCode is 401 with an empty bodyBytes, so it returns 'nil, false'. I couldn't get detailed information. Is this an issue with the API server?

After reviewing the doc again, the 401 means

> 401
Unauthorized
The JSON Web Token (JWT) in the authorization header is invalid. For more information, see [Generating JSON Web Tokens for API requests](https://developer.apple.com/documentation/appstoreserverapi/generating_json_web_tokens_for_api_requests).

Please double check those KeyID, BundleID, Issuer, and KeyContent are correct. @takeone90

**Comment by takeone90** [comment]
@richzw 
KeyID, BundleID, Issuer, and KeyContent are all the same as in Production. The only difference is that StoreConfig.Sandbox=true.
And with this information, the Production receipt verification works fine.
Do I need to get a different key for the sandbox?

**Comment by takeone90** [comment]
@richzw 
Oh my god, I found the worst mistake... One of the letters in the BundleID was uppercase... I'm sorry.
Thank you so much, you've helped me cut down on a lot of wasted time.
