### ISSUE TITLE
IOS server api refund transaction revocation reason gives unexpected value

### ISSUE THREAD

**Issue by fans3210** [awa/go-iap#284]
{TransactionID:2000000615381732 OriginalTransactionId:2000000615381732 WebOrderLineItemId: BundleID:com.xx.xx ProductID:com.apple.test.pkg.newbie SubscriptionGroupIdentifier: PurchaseDate:1717150790000 OriginalPurchaseDate:1717150790000 ExpiresDate:0 Quantity:1 Type:Consumable AppAccountToken:13bacc6b-0cbb-4a96-82fd-b479c1fa15e7 InAppOwnershipType:PURCHASED SignedDate:1717382214922 OfferType:0 OfferIdentifier: RevocationDate:1717154566000 RevocationReason:0x40021c8278 IsUpgraded:false Storefront:SGP StorefrontId:143464 TransactionReason:PURCHASE Environment:Sandbox Price:980 Currency:SGD OfferDiscountType:}, RevocationReason = 274913329784

From documentation the RevocationReason should only be 0 or 1

**Comment by richzw** [comment]
The `RevocationReason:0x40021c8278` seems one address of struct. You may change the definition of `RevocationReason` to `int` type and check the value again? @fans3210

**Comment by richzw** [comment]
> Thanks for the quick reply. Yes I also printed it out and RevocationReason = 274913329784 @richzw

It seems the value of RevocationReason returned from iOS is invalid, you may ask question on https://developer.apple.com/forums/

**Comment by fans3210** [comment]
@richzw . Strange thing is I tried to use app store server library to decode the transaction and got the correct revocation reason which is 0- >others

refund transaction:  JWSTransactionDecodedPayload(originalTransactionId='2000000615381732', transactionId='2000000615381732', webOrderLineItemId=None, bundleId='xxx', productId='com.apple.test.pkg.newbie', subscriptionGroupIdentifier=None, purchaseDate=1717150790000, originalPurchaseDate=1717150790000, expiresDate=None, quantity=1, type=<Type.CONSUMABLE: 'Consumable'>, rawType='Consumable', appAccountToken='13bacc6b-0cbb-4a96-82fd-b479c1fa15e7', inAppOwnershipType=<InAppOwnershipType.PURCHASED: 'PURCHASED'>, rawInAppOwnershipType='PURCHASED', signedDate=1717644403140, revocationReason=<RevocationReason.REFUNDED_DUE_TO_ISSUE: 1>, rawRevocationReason=1, revocationDate=1717154566000, isUpgraded=None, offerType=None, rawOfferType=None, offerIdentifier=None, environment=<Environment.SANDBOX: 'Sandbox'>, rawEnvironment='Sandbox', storefront='SGP', storefrontId='143464', transactionReason=<TransactionReason.PURCHASE: 'PURCHASE'>, rawTransactionReason='PURCHASE', currency='SGD', price=980, offerDiscountType=None, rawOfferDiscountType=None)

**Comment by fans3210** [comment]
I changed revocationreason field from pointer to int32 and got the expected value 1

**Comment by richzw** [comment]
> I changed revocationreason field from pointer to int32 and got the expected value 1 Noticed that the wrong decimal value previously of 274913329784 is just decimal value of the memory address of the *int32 revocation reason

It seems the definition should be `type RevocationReason int32` ? @fans3210

**Comment by fans3210** [comment]
Yes seems this would resolve the issue but not sure whether is the correct approach since I also checked apple's implementation of appstore server library python version and they indeed make this field an optional value:
<img width="774" alt="Screenshot 2024-06-06 at 12 10 03 PM" src="https://github.com/awa/go-iap/assets/6023208/7ebd4885-e638-468d-8c44-67c4c41f4388">
<img width="582" alt="Screenshot 2024-06-06 at 12 11 10 PM" src="https://github.com/awa/go-iap/assets/6023208/c0268b80-a6fc-4b1e-be00-c2b98e958d94">

**Comment by richzw** [comment]
> I changed revocationreason field from pointer to int32 and got the expected value 1 Noticed that the wrong revocationreason value previously mentioned(274913329784) is just decimal format of the memory address of the *int32 revocation reason

Sorry for misunderstanding before. I am confused that the revocation reason is defined as `type RevocationReason int` in this library. You mentioned that ` I changed revocationreason field from pointer to int32`.  Could you please give more details of your test codes?

Refer the java implementation of apple [app-store-server-library-java](https://github.com/apple/app-store-server-library-java/tree/main)/

```java
public enum RevocationReason {

    REFUNDED_DUE_TO_ISSUE(1),
    REFUNDED_FOR_OTHER_REASON(0);

    private final Integer value;
```

The type of revocation reason is Integer.  it could be considered the same type `int` in golang roughly. @fans3210

**Comment by fans3210** [comment]
> Could you please give more details of your test codes?

Sure. My test code is very simple, I just change the type of RevocationReason field from *int32 to int32 and found it able to be decoded to the correct value which is 1 using a signed payload I previously used while retrieve with the getresundhitory api.
So I think change to int32 or int should work.

**Comment by fans3210** [comment]
Sorry for the update. I think the library currently using a pointer of int32 has no issue. It's my own fault. I'm not able to reproduce it anymore. Maybe previously I forgot to deference the *int32 when print. Any way, I'm not able to reproduce it. I would close this issue. So sorry for the inconvenience caused.
