### ISSUE TITLE
Check whether the token has expired a few minutes earlier

### ISSUE THREAD

**Issue by leeqvip** [awa/go-iap#289]
```
// GenerateIfExpired checks to see if the token is about to expire and generates a new token.
func (t *Token) GenerateIfExpired() (string, error) {
	t.Lock()
	defer t.Unlock()

	if t.Expired() || t.Bearer == "" {
		err := t.Generate()
		if err != nil {
			return "", err
		}
	}

	return t.Bearer, nil
}

// Expired checks to see if the token has expired.
func (t *Token) Expired() bool {
	return time.Now().Unix() >= t.ExpiredAt
}
```

Due to time difference or network delay, when the request reaches the Apple service, the token has expired.

**Comment by richzw** [comment]
@leeqvip The `ExpiredAt` could be set through  [`ExpiredAtFunc` func](https://github.com/awa/go-iap/blob/master/appstore/api/token.go#L33), and this `ExpiredAt` could set less than one hour, such as several minutes earlier than one hour expired time.
