### ISSUE TITLE
Get subscription for user from playstore

### ISSUE THREAD

**Issue by KarineAyrs** [awa/go-iap#294]
Hi! Is there a feature in this package to get a subscription from the playstore using purchaseToken? Perhaps there is some kind of implementation for this https://developers.google.com/android-publisher/api-ref/rest/v3/purchases.subscriptionsv2/get ? I couldn't find it in the documentation.

**Comment by takecy** [comment]
Hi @KarineAyrs.
This function would be the one to do that.
Please check :)
https://github.com/awa/go-iap/blob/4de7477bda65e12a6f742b48487305199d87450e/playstore/validator.go#L146-L156

**Comment by KarineAyrs** [comment]
Thanks!

**Comment by KarineAyrs** [comment]
One more question) I can't find notification type `SUBSCRIPTION_ON_HOLD` for google subscription, maybe there is a reason why this type of notification was not added?

**Comment by takecy** [comment]
I don't think there's any particular reason for this, it's just that an addition was missed 🤔

**Comment by KarineAyrs** [comment]
will you add it?)

**Comment by richzw** [comment]
> SUBSCRIPTION_ON_HOLD

The `SubscriptionNotificationTypeAccountHold` is equal to `(5) SUBSCRIPTION_ON_HOLD ` , since both of them are `5`.

**Comment by takecy** [comment]
I checked the documentation again.
https://developer.android.com/google/play/billing/rtdn-reference#sub
`SUBSCRIPTION_ON_HOLD` is numbered `5`.

This means the following definitions.
There was already a definition 🙏 
https://github.com/awa/go-iap/blob/4de7477bda65e12a6f742b48487305199d87450e/playstore/notification.go#L11

**Comment by takecy** [comment]
@richzw Thanks 😁

**Comment by KarineAyrs** [comment]
thanks! I should have been more careful)
