### ISSUE TITLE
Google App Engine compatibility

### ISSUE THREAD

**Issue by pjebs** [awa/go-iap#30]
# Introduction

Google App Engine is a sandboxed environment. We can't make calls to the outside world without using the `net/http`'s `Request` to create a `http.Client` by:

```
import (
        "net/http"

        "google.golang.org/appengine"
        "google.golang.org/appengine/urlfetch"
)
ctx := appengine.NewContext(r)
client := urlfetch.Client(ctx)
```

Without doing that, the library doesn't work.

The way Stripe-Go-Library handles it is like this: https://github.com/stripe/stripe-go#google-appengine

Basically Stripe allows Google App Engine users the ability to feed in their own `http Client` and the library will then use that.

```
    ctx := appengine.NewContext(r)
    httpClient := urlfetch.Client(ctx)

    sc := client.New(key, stripe.NewBackends(httpClient))
```

The way I handle it is like this:

https://github.com/pjebs/optimus-go/blob/master/gae.go
https://github.com/pjebs/optimus-go/blob/master/standalone.go

My way may be a lot easier to implement.

In your code, everytime you refer to a http Client, you instead call: `client()` from the files above.

There will be no affect to the rest of your code.
# More information

https://cloud.google.com/appengine/docs/go/issue-requests
https://cloud.google.com/appengine/docs/go/urlfetch/reference

**Comment by pjebs** [comment]
Since you are using `gorequest` library @L102(https://github.com/dogenzaka/go-iap/blob/master/appstore/validator.go#L102)

**Comment by mltucker** [comment]
I think it's not as simple since the client this library creates has the jsonKey baked in.

My current code looks like this:

```
func New(ctx context.Context, jsonKey []byte) (Client, error) {
	//conf, err := google.JWTConfigFromJSON(jsonKey, androidpublisher.AndroidpublisherScope)
	tokenSource, err := google.JWTAccessTokenSourceFromJSON(jsonKey, "myapp-123456.appspot.com")

	if err != nil {
		return Client{}, err
	}

	httpClient := &http.Client{
		Transport: &oauth2.Transport{
			Source: tokenSource,
			Base: &urlfetch.Transport{
				Context: ctx,
			},
		},
	}

	return Client{
		httpClient: httpClient,
	}, err
}

```

But I'm getting an error in VerifyProduct: `error: googleapi: Error 401: Invalid Credentials, authError`.  I'm not sure if the problem is using `"myapp-123456.appspot.com"` as my `audience` in the call to `google.JWTAccessTokenSourceFromJSON` or if it's something else.

**Comment by mltucker** [comment]
I'm doing app store verification manually.  But to get play store verification working, I copied the playstore/validator.go to my project and edited it.  Gist here:

https://gist.github.com/mltucker/db4df00918d7b917f49b60012b615c02
