### ISSUE TITLE
In app store review. Need help

### ISSUE THREAD

**Issue by erikd234** [awa/go-iap#301]
Hi my production server is running sandbox = false.

I see that in app store review they test with sandbox but my app points to my production envirnment

I also see this on apples website

`If you don’t have environment information, follow these steps:

Call the endpoint using the production URL. If the call succeeds, the transaction identifier belongs to the production environment.

If you receive an error code 4040010 [TransactionIdNotFoundError](https://developer.apple.com/documentation/appstoreserverapi/transactionidnotfounderror), call the endpoint using the sandbox environment.

If the call succeeds, the transaction identifier belongs to the sandbox environment. If the call fails with the 4040010 error code, the transaction identifier isn’t present in either environment.`

Is this properly implemented in go iap for app store transaction verification?

Thanks!

**Comment by richzw** [comment]
@erikd234 , The verify function to appstore server api was added now, please refer to https://github.com/awa/go-iap/blob/master/appstore/api/validator.go#L26 , if you have any more question please let me know.

**Comment by erikd234** [comment]
thank you this is amazing! Thanks for the fast reply. I will implement this on my validation handler.

Quick question.

Why return an interface instead of the concrete type?

**Comment by richzw** [comment]
> thank you this is amazing! Thanks for the fast reply. I will implement this on my validation handler.
> 
> Quick question.
> 
> Why return an interface instead of the concrete type?

1. make consistency with the verify signature https://github.com/awa/go-iap/blob/master/appstore/validator.go#L29
2. In case of the return type could be changed in future, the interface is used here.

@erikd234

**Comment by erikd234** [comment]
But if the return type changes, and I use that function signature. my code will just break no? Is there a way to make that return a concrete type so we have type safety on that function call?

**Comment by richzw** [comment]
> Thanks for your input! It would be a smart solution to the problem if we can accommodate generics in the future.
> 
> It seems problematic to support generics only for this part, so I think it is better to support @richzw PR.

Agree.

------


@erikd234, I am glad to discuss this with you, Could you please try the latest version? If you have any questions, please let me know.

**Comment by erikd234** [comment]
I see that you have changed it to a concrete type 


```
func (c *APIClient) Verify(ctx context.Context, transactionId string) (***TransactionInfoResponse**, error) {
	result, err := c.productionCli.GetTransactionInfo(ctx, transactionId)
	if err != nil && errors.Is(err, TransactionIdNotFoundError) {
		result, err = c.sandboxCli.GetTransactionInfo(ctx, transactionId)
	}
	return result, err
}
```

Much appreciated!

BTW our app just got accepted thank you so much :)

**Comment by bububa** [comment]
This implementation have problem in sandbox env. The transaction does not exists in product env, the api response status code is 401 not TransactionIdNotFoundError
