### ISSUE TITLE
How to pass receipt in ios?

### ISSUE THREAD

**Issue by zhanswift** [awa/go-iap#73]
I want to do method in API to purchase products. How to do it? How to pass receipt from API? What does the recipe consist of?

    package main

    import (
	  "github.com/awa/go-iap/appstore"
    )

    func main() {
	  r := mux.NewRouter()
	  r.Handle("/iaptest", IAPTest).Methods("GET")
	  fmt.Println("Server is runned on port 3000")
	  if err := http.ListenAndServe(":3000", handlers.LoggingHandler(os.Stdout, r)); err != nil {
		  log.Fatal(err)
	  }
    }
    var IAPTest = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	  client := appstore.New()
	  req := appstore.IAPRequest{
		  ReceiptData: "your receipt data encoded by base64",
	  }
	  resp := &appstore.IAPResponse{}
	  ctx := context.Background()
	  err := client.Verify(ctx, req, resp)
    })

**Comment by jun06t** [comment]
I think you misunderstood.
We can get the request receipt **from Client(iOS/Android) Application**.
This library enables you to verify the receipt via AppStore API.

1. User purchases a product or a subscription on the client application.
1. The client sends the receipt to the server.
1. The server sends the receipt to the AppStore API with this library.

**Comment by zhanswift** [comment]
> I think you misunderstood.
> We can get the request receipt **from Client(iOS/Android) Application**.
> This library enables you to verify the receipt via AppStore API.
> 
> 1. User purchases a product or a subscription on the client application.
> 2. The client sends the receipt to the server.
> 3. The server sends the receipt to the AppStore API with this library.

And what exactly will do library?
