### ISSUE TITLE
Apple store verify not check status is 0. 

### ISSUE THREAD

**Issue by jaggerwang** [awa/go-iap#78]
I send arbitrary receipt data to verify, but got a success result, as the err is nil. Because it not check the `Status` in response, as the following screenshot shows.

![image](https://user-images.githubusercontent.com/1255011/48658578-805b1880-ea7f-11e8-8cd6-4cec9c13cf02.png)

**Comment by haritsfahreza** [comment]
Hi @jaggerwang!

In my assumption, the status must be checked by ourselves to make it flexible. AFAIK, the only status that the SDK checked is when it get 21007, and request it to the sandbox URL, following the best practice of Apple IAP.

Hope that answer your concern.

**Comment by kabouzeid** [comment]
This is not an issue. You are responsible for evaluating the response and thus the status.
