### ISSUE TITLE
Can I verify receipt before send to Apple server?

### ISSUE THREAD

**Issue by zhanswift** [awa/go-iap#81]
Can I verify receipt before send to Apple server? If yes how to do?

**Comment by haritsfahreza** [comment]
Hi @zhanswift!

I'm afraid we can't do that, based on the Apple IAP docs. To get the receipt data, you must request to the Apple `verifyReceipt` API. After that, you may validate the receipt based on the original transaction ID, environment, bundle ID, product ID and all of the fields that provided from the `/verifyReceipt` API response

Hope this is answer your question.
