### ISSUE TITLE
How to verify to sandbox url while testing?

### ISSUE THREAD

**Issue by dzpt** [awa/go-iap#82]
I see Client has both Production URL and Sandbox URL.
But there is no mentioned way to verify to sandbox URL?

**Comment by haritsfahreza** [comment]
Hi @aaveidt ! same issue here.

How about if we add a new param on the `appstore.New` to define which URL we need to use?

**Comment by aaveidt** [comment]
@haritsfahreza i suppose it would be the good solution.

**Comment by haritsfahreza** [comment]
Just got some reference on this @aaveidt https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store

```
Important

Verify your receipt first with the production URL; proceed to verify with the sandbox URL if you receive a 21007 status code. Following this approach ensures that you do not have to switch between URLs while your application is tested, reviewed by App Review, or live in the App Store.
```
This SDK already following the best practice

**Comment by kabouzeid** [comment]
Should be closed, as @haritsfahreza said the implementation already does the right thing and falls back to sandbox server.
