### ISSUE TITLE
Add new release version with Google Play Developer API v3

### ISSUE THREAD

**Issue by maksymkotov** [awa/go-iap#97]
From android developers blog:
> Starting December 1, 2019, versions 1 and 2 of the Google Play Developer API will no longer be available so you need to update to version 3 ahead of this date.

Can you make a release?

**Comment by jun06t** [comment]
I've released [v1.1.0](https://github.com/awa/go-iap/releases/tag/v1.1.0) :-)
Plz use this.

**Comment by maksymkotov** [comment]
Thanks!
